# Create a Role in the default namespace that grants access to the Agones api
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agones-api-explorer
  namespace: default
  labels:
    app: agones-api-explorer
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["stable.agones.dev"]
  resources: ["fleetallocations"]
  verbs: ["create"]
- apiGroups: ["stable.agones.dev"]
  resources: ["fleets", "fleet", "gameservers", "gameserver"]
  verbs: ["get", "watch", "list"]

---
# Create a ServiceAccount that will be bound to the above role
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-api-explorer
  namespace: default
  labels:
    app: agones-api-explorer

---
# Bind the agones-api-explorer ServiceAccount to the agones-api-explorer Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agones-api-explorer
  namespace: default
  labels:
    app: agones-api-explorer
subjects:
- kind: ServiceAccount
  name: agones-api-explorer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agones-api-explorer
